# Diego Zegarra G01234361
# CS 262, Lab Section 207
# Project 1

CC=gcc

	
gFLAGS = -Wall -g -O2 -std=c89 -D_XOPEN_SOURCE=600 -pedantic-errors

ggb: Project1

LIBS=-lm

all: $(TARGET)

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c $(LIBS)

clean:
	rm $(TARGET)





